services:
  postgres:
    container_name: postgres-sql-halley
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2334
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: halley_ecommerce
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped
  redis:
    container_name: redis-halley
    image: redis:latest
    command: redis-server --notify-keyspace-events Ex
    ports:
      - 6379:6379
    networks:
      - spring-demo
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" #For connection
      - "15672:15672" # for management framework
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

      
volumes:
  postgres:
    driver: local
networks:
  spring-demo:
    driver: bridge