services:
  postgres:
    container_name: postgres-sql-halley
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2334
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: halley_ecommerce
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped
  redis:
    container_name: redis-halley
    image: redis:latest
    command: redis-server --notify-keyspace-events Ex
    ports:
      - 6379:6379
    networks:
      - spring-demo
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.10.18-management
    container_name: rabbitmq
    ports:
      - "5672:5672" #For connection
      - "15672:15672" # for management framework
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    environment:
      - discovery.type= single-node
      - xpack.security.enabled= false
    ports:
      - "9200:9200"
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1



      
volumes:
  postgres:
    driver: local
  es-data:
networks:
  spring-demo:
    driver: bridge