spring:
  application:
    name: halley-ecommerce
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING.MAIL.USERNAME}
    password: ${SPRING.MAIL.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  admin:
    email: ${SPRING.ADMIN.EMAIL}
    password: ${SPRING.ADMIN.PASSWORD}
  docker:
    compose:
      lifecycle-management: start_only

  rabbitmq:
    host: rabbitmq
    port: 5672
    stream:
      username: guest
      password: guest
    queue:
      orderMailQueueMember: orderMailQueueMember
      orderMailQueueNonMember: orderMailQueueNonMember
      orderShippedQueue: orderShippedQueue
      registrationQueue: registrationQueue
      resetPassword: resetPassword
    template:
      routing-key:
        order:
          member: halley_routing_key_member
          nonmember: halley_routing_key_non_member
          shipped: halley_routing_key_shipped_member
        registration: halley_registration_routing_key
        reset-password: halley_routing_key_reset_password
      exchange: halley_exchange
  main:
    allow-bean-definition-overriding: true

  elasticsearch:
    uris: localhost:9200
    connection-timeout: 10s
    socket-timeout: 5s


  cache:
    cache-names: allBrand,categoryTree,mainCategories,products,findById,findByCategoryId,find_by_search,similarProducts,
                find_all_by_brand,findByColor
    caffeine:
      spec: maximum-size=100,expireAfterWrite=25s





server:
  servlet:
    context-path: /api/v1/
logging:
  level:
    root: info
  file:
    name: logs/halley-dev.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

